name: Build Master
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        java:
          - '11.0.5'
          - '17'
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build
        run: |
          ./gradlew -S -Pskip.signing assemble
          unset GEM_PATH GEM_HOME JRUBY_OPTS
          ./gradlew -S -Pskip.signing clean build
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Assemble
        shell: cmd
        run: |
          gradlew.bat -i assemble
      - name: Check
        shell: cmd
        run: |
          gradlew.bat -i -S clean build


